"""add request timestamps and indexes

Revision ID: 427d408999fd
Revises: 39b247901e87
Create Date: 2026-08-23 19:23:34.472822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427d408999fd'
down_revision: Union[str, Sequence[str], None] = '39b247901e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('ix_requests_email', 'requests', ['email'], unique=False)
    op.create_index('ix_requests_status', 'requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_status', table_name='requests')
    op.drop_index('ix_requests_email', table_name='requests')
    op.drop_index('ix_requests_created_at', table_name='requests')
    op.drop_column('requests', 'updated_at')
    # ### end Alembic commands ###
